DataBiosphere/job-manager

servers/cromwell/jobs/controllers/jobs_controller.py
servers/cromwell/jobs/test/test_jobs_controller.py

Re-opening #145 with a clean commit history. I force pushed `master` back one commit and then applied all the changes on top of this. 
@rexwangcc can you make sure this has all of your changes?

Implement the function to update labels for Cromwell jobs

---

ui/src/app/shared/header/header.component.html

Error encountered upon attempting to deploy.

[UI] Fix assignChipValue() invocation

---

package-lock.json
ui/package-lock.json
ui/package.json

Also may need to run the following after this change:
```
npm install -g @angular/cli # May be unnecessary
npm install @angular/cli
docker-compose -f _.yml build
```
Remove seemingly accidental check-in of root level package lock.

Upgrade @angular/cli to avoid vulnerable dependency

---

servers/dsub/jobs/controllers/jobs_controller.py
servers/dsub/jobs/test/base_test_cases.py
servers/dsub/jobs/test/test_jobs_controller_google.py
servers/dsub/jobs/test/test_jobs_controller_local.py

- Implement querying by end datetime
- Minor cleanup in tests to shorten a couple function names and make it more readable

[dsub] Implement querying by end date

---

servers/dsub/jobs/controllers/jobs_controller.py
servers/dsub/jobs/test/base_test_cases.py
servers/dsub/jobs/test/test_jobs_controller_google.py

[dsub] Support querying by 'Submitted' status

---

ui/src/app/shared/header/header.component.spec.ts
ui/src/app/shared/header/header.component.ts

I double checked the behavior, it's WAI

Fix the end date tooltip

---

ui/src/app/projects/projects.component.css
ui/src/app/projects/projects.component.html
ui/src/app/projects/projects.component.ts

- Focus the project search bar on initial page load
- Selecting an autocompleted project (via click or enter key) initiates navigation
- Remove unused imports

[UI] Projects page interaction improvements

---

ui/src/app/job-details/resources/resources.component.spec.ts
ui/src/app/job-details/resources/resources.component.ts

Also add the log file tabs once we download them and verify they exist.

[UI] Don't show input/output tabs when there are none

---

servers/cromwell/README.md

Fix steps in Cromwell README after merging from master 😞

Fix README ordering

---

README.md
servers/cromwell/.swagger-codegen-ignore

Needed to add line to cromwell/.swagger-codegen-ignore to cover it

fixed issue with cromwell swagger codegen

---

ui/src/app/testing/fake-capabilities.service.ts
ui/src/app/testing/fake-gcs.service.ts
ui/src/app/testing/fake-job-manager.service.ts
ui/src/tsconfig.app.json

Drop now unneeded `@Injectable` annotation from these fake services.

Don't compile test-only services into main app

---

ui/src/app/job-list/job-list.component.css
ui/src/app/job-list/job-list.component.html
ui/src/app/job-list/job-list.component.spec.ts
ui/src/app/job-list/job-list.module.ts

Fix query builder header to top of page on job list view. Still have to fix the column headers but will address that in a separate PR.

[UI] Fix header to top of page on scroll

---

ui/src/app/job-list/table/table.component.css
ui/src/app/job-list/table/table.component.html
ui/src/app/job-list/table/table.component.spec.ts
ui/src/app/job-list/table/table.component.ts

Fix footer to bottom of page and conditionally add padding to table when shown.

[UI] Fix selection footer

---

ui/.angular-cli.json
ui/package-lock.json
ui/package.json
ui/src/app/job-details/job-details.component.spec.ts
ui/src/app/job-details/job-details.module.ts
ui/src/app/job-details/tasks/tasks.component.css
ui/src/app/job-details/tasks/tasks.component.html
ui/src/app/job-details/tasks/tasks.component.spec.ts
ui/src/app/job-details/tasks/tasks.component.ts
ui/src/app/job-list/job-list.component.spec.ts
ui/src/app/job-list/job-list.module.ts
ui/src/app/job-list/table/table.component.css
ui/src/app/job-list/table/table.component.html
ui/src/app/job-list/table/table.component.spec.ts
ui/src/app/job-list/table/table.component.ts
ui/src/app/shared/common.ts

- replaced status icons with clarity icons and tooltips
- combined log columns into one and replaced links with clarity icons and tooltips

Implement log icons update

---

ui/src/app/app-routing.module.ts
ui/src/app/app.module.ts
ui/src/app/dashboard/dashboard.component.html
ui/src/app/dashboard/dashboard.component.spec.ts
ui/src/app/dashboard/dashboard.component.ts
ui/src/app/dashboard/dashboard.module.ts
ui/src/app/projects/projects.component.ts
ui/src/app/shared/utils/url-search-params.utils.ts
ui/src/environments/environment.cromwell.caas.ts
ui/src/environments/environment.cromwell.dev.ts
ui/src/environments/environment.dsub.google.ts
ui/src/environments/environment.dsub.local.ts
ui/src/environments/environment.ts

Add dashboard page to routing and set a flag in environment files.

Empty dashboard wired into routing

---

servers/dsub/jobs/controllers/capabilities_controller.py
servers/dsub/jobs/controllers/utils/query_parameters.py
servers/dsub/jobs/test/base_test_cases.py
servers/dsub/requirements-to-freeze.txt
servers/dsub/requirements.txt

Needed to bump the dsub version to latest as well. `0.1.5` was throwing an error on `lookup_job_tasks` for the local provider.

[dsub] Fix local provider

---

servers/dsub/jobs/controllers/aggregation_controller.py
ui/src/app/dashboard/dashboard.component.spec.ts
ui/src/app/dashboard/dashboard.module.ts
ui/src/app/dashboard/grouped-summary/grouped-summary.component.html
ui/src/app/dashboard/grouped-summary/grouped-summary.component.spec.ts
ui/src/app/dashboard/grouped-summary/grouped-summary.component.ts
ui/src/app/dashboard/total-summary/total-summary.component.html
ui/src/app/dashboard/total-summary/total-summary.component.spec.ts
ui/src/app/dashboard/total-summary/total-summary.component.ts
ui/src/app/testing/fake-aggregation.service.ts

Please help improve the PR, thanks!

Added link to status counts on dashboard page.

---

servers/cromwell/README.md

I made a typo in the previous PR, need to fix it in this PR.

Fix a typo in readme

---

README.md
servers/cromwell/README.md
servers/dsub/README.md

Changes in-place: https://github.com/DataBiosphere/job-manager/blob/cjl_getting_started/README.md

A few minor changes to the Cromwell getting started process docs

---

servers/cromwell/jobs/controllers/utils/task_statuses.py
servers/cromwell/jobs/test/test_task_statuses.py

This PR addresses the issue #334 .

Update the task status mappings.

---

servers/cromwell/README.md

I noticed some errors in the sample JSON, possibly introduced by my last PR (#307)
Note that I made the JSON syntactically valid, I haven't checked that it's a JMUI configuration (could somebody verify?)

Fix config example JSON

---

api/jobs.yaml
servers/cromwell/jobs/controllers/jobs_controller.py
servers/cromwell/jobs/swagger/swagger.yaml
servers/dsub/jobs/controllers/capabilities_controller.py
servers/dsub/jobs/controllers/jobs_controller.py
servers/dsub/jobs/controllers/utils/query_parameters.py
servers/dsub/jobs/swagger/swagger.yaml
servers/dsub/jobs/test/base_test_cases.py
ui/src/app/shared/common.ts
ui/src/app/shared/utils/url-search-params.utils.ts

- add submission to the regular query builder and API
- take submission out of the queryExtensions endpoint for dsub
- add submission to the query request for cromwell

Add full support for submission time

---

ui/src/app/app.component.spec.ts
ui/src/app/core/initial-error/initial-error.component.css
ui/src/app/core/initial-error/initial-error.component.html
ui/src/app/core/initial-error/initial-error.component.ts

Reassure people that they have indeed reached Job Manager, and that it is running, but there's a problem with navigation or reaching Cromwell (or dsub... neutrally worded).
This will probably get restyled along with the rest of Job Manager anyway, hence the "enterprise CRM system circa 1995" aesthetic.
Closes https://github.com/DataBiosphere/job-manager/issues/442

Slightly improve upon the default error message

---

api/jobs.yaml
servers/cromwell/jobs/controllers/jobs_controller.py
servers/cromwell/jobs/test/test_jobs_controller.py
ui/src/app/job-details/tasks/tasks.component.css
ui/src/app/job-details/tasks/tasks.component.html
ui/src/app/job-details/tasks/tasks.component.ts

- added icon to indicate a call-cached task
- moved shard status icon into the same position for consistency
Closes #498

Added icon to task list that indicates task was call-cached

---

.circleci/config.yml
ui/src/app/job-list/job-list.component.spec.ts
ui/src/app/shared/header/header.component.ts

reclassify 'Aborted' as a 'Failed' job state

---

deploy/quickstart/quick_start.py

added hashbang to generated jmui_start.sh

---

servers/cromwell/jobs/controllers/jobs_controller.py
ui/src/app/job-details/failures/failures.component.ts
ui/src/app/job-details/job-details.component.html
ui/src/app/job-details/job-details.component.ts
ui/src/app/job-details/job-details.module.ts
ui/src/app/job-details/panels/panels.component.css
ui/src/app/job-details/panels/panels.component.html
ui/src/app/job-details/panels/panels.component.spec.ts
ui/src/app/job-details/panels/panels.component.ts
ui/src/app/job-details/resources/resources.component.ts
ui/src/app/job-details/tasks/tasks.component.css
ui/src/app/job-details/tasks/tasks.component.html
ui/src/app/job-details/tasks/tasks.component.spec.ts
ui/src/app/job-details/tasks/tasks.component.ts

- add icon to sub-job details page
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/1713505/49829865-95b12300-fd5d-11e8-8b94-b84862726f2e.png"><img src="https://user-images.githubusercontent.com/1713505/49829865-95b12300-fd5d-11e8-8b94-b84862726f2e.png" alt="image" style="max-width:100%;"></a>
- maintain query filters from job list page
Closes #536

Add 'Navigate Up' arrow to sub-job details

---

ui/src/app/job-details/panels/panels.component.css
ui/src/app/job-details/panels/panels.component.html
ui/src/app/job-details/panels/panels.component.ts

added job status and icon to 'Status' card

---

CHANGELOG.md
ui/src/app/shared/header/chips/filter-chip.component.ts
ui/src/app/shared/header/header.component.ts

take out check for exhaustive when contructing a new paginator

---

deploy/quickstart/quick_start.py
servers/dsub/jobs/controllers/jobs_controller.py
servers/dsub/jobs/test/base_test_cases.py
ui/src/app/core/auth.service.ts
ui/src/app/job-details/common/failures-table/failures-table.component.ts
ui/src/app/job-details/resources/resources-table/resources-table.component.ts
ui/src/app/job-details/tabs/tabs.component.spec.ts
ui/src/app/job-details/tabs/tabs.component.ts
ui/src/app/shared/utils/resource-utils.ts

Include authuser on GCS links

---

CHANGELOG.md
servers/cromwell/jobs/controllers/jobs_controller.py
ui/src/app/core/initial-error/initial-error.component.html
ui/src/app/core/initial-error/initial-error.component.ts

Throw 401 errors from Cromwell API, catch them in the UI

---

CHANGELOG.md

v0.5.7 was missed, new items are actually for v0.5.8

updated CHANGELOG to include missed release

---

CHANGELOG.md
api/jobs.yaml

Modify swagger yaml regex for job id

---

CHANGELOG.md
servers/cromwell/jobs/controllers/jobs_controller.py

added includeKey to metadata to reduce size of response from Cromwell

---

api/jobs.yaml
servers/cromwell/jobs/controllers/jobs_controller.py
servers/cromwell/jobs/test/test_jobs_controller.py
servers/cromwell/jobs/test/test_task_statuses.py
ui/src/app/job-details/tabs/tabs.component.html
ui/src/app/job-details/tabs/tabs.component.spec.ts
ui/src/app/job-details/tabs/tabs.component.ts
ui/src/app/job-details/tabs/timing-diagram/timing-diagram.component.ts

Represent individual shards in timing diagram

---

CHANGELOG.md
ui/src/app/job-details/common/debug-icons/debug-icons.component.css
ui/src/app/job-details/common/failures-table/failures-table.component.css
ui/src/app/job-details/panels/panels.component.css
ui/src/app/job-details/resources/resources-table/resources-table.component.css
ui/src/app/job-details/tabs/tabs.component.css
ui/src/app/job-details/tabs/tabs.component.html

added Terra-like styling to Job Details page tabs

---

ui/package-lock.json
ui/package.json

Closes #650 
I totally muddled my way through this, having never used `npm` before.
The A/C of local dev working again appears to be met.

Specify latest node-sass in package.json

---

CHANGELOG.md
ui/src/app/core/auth.service.ts
ui/src/app/sign-in/sign-in.component.ts

added check in sign-in service
Closes https://broadworkbench.atlassian.net/browse/BA-5663

Do not trigger autologout when there is nothing configured

---

CHANGELOG.md
ui/src/app/job-details/job-details.component.spec.ts
ui/src/app/job-details/panels/panels.component.css
ui/src/app/job-details/panels/panels.component.html
ui/src/app/job-details/panels/panels.component.spec.ts
ui/src/app/job-details/panels/panels.component.ts

Closes https://broadworkbench.atlassian.net/browse/BA-5370

added Abort Job button to the Job Details page [BA-5370]

---

CHANGELOG.md
servers/cromwell/jobs/controllers/jobs_controller.py
servers/cromwell/jobs/test/test_jobs_controller.py
servers/dsub/jobs/controllers/jobs_controller.py
servers/dsub/jobs/controllers/utils/jobs_generator.py
servers/dsub/jobs/test/base_test_cases.py
servers/dsub/jobs/test/test_jobs_controller_google.py
servers/dsub/jobs/test/test_jobs_controller_google_v2.py
servers/dsub/jobs/test/test_jobs_controller_local.py
servers/jm_utils/jm_utils/test/test_page_tokens.py
ui/src/app/core/auth.service.ts
ui/src/app/job-details/common/debug-icons/debug-icons.component.html
ui/src/app/job-details/common/debug-icons/debug-icons.component.ts

Closes https://broadworkbench.atlassian.net/browse/BA-5815

two small bug fixes [BA-5815]

---

CHANGELOG.md
servers/cromwell/jobs/controllers/jobs_controller.py

Closes https://broadworkbench.atlassian.net/browse/BA-5874

aligned types/timezones of start, end and now dates [BA-5874]

---

ui/src/app/job-details/common/debug-icons/debug-icons.component.css

Closes https://broadworkbench.atlassian.net/browse/BA-5894

grey out disabled backend log in errors card [BA-5894]

---

CHANGELOG.md
ui/src/app/job-details/common/debug-icons/debug-icons.component.ts
ui/src/app/job-details/panels/panels.component.css
ui/src/app/job-details/panels/panels.component.html
ui/src/app/job-details/panels/panels.component.spec.ts
ui/src/app/job-details/panels/panels.component.ts

Closes https://broadworkbench.atlassian.net/browse/BA-5788.

added a link to the top-level execution directory [BA-5788]

---

CHANGELOG.md
api/jobs.yaml
servers/cromwell/jobs/controllers/jobs_controller.py
servers/cromwell/jobs/test/test_jobs_controller.py
ui/src/app/job-details/tabs/timing-diagram/timing-diagram.component.ts

non-scattered
scattered
Closes https://broadworkbench.atlassian.net/browse/BA-5905.

Include all attempts in Timing Diagram [BA-5905]

---

CHANGELOG.md
servers/cromwell/jobs/controllers/jobs_controller.py

Closes https://broadworkbench.atlassian.net/browse/BA-5910

Don't treat preempted attempts as failures [BA-5910]

---

CHANGELOG.md
ui/src/app/job-details/job-details.component.ts
ui/src/app/job-details/resources/resources-table/resources-table.component.ts
ui/src/app/job-details/tabs/tabs.component.html
ui/src/app/job-details/tabs/tabs.component.ts

Closes https://broadworkbench.atlassian.net/browse/WA-72

prompt population of inputs and outputs upon navigation up or down [WA-72]

---

ui/package-lock.json
ui/package.json

Resolves security issues in *non-dev* dependencies. After applying these updates I brought up the app locally and clicked around through everything I could see, seems to work normally.

Security updates [BT-606]

---

README.md
TERRA_QUICKSTART.md

Would be great to have at least one person perform these steps locally to ensure I'm not forgetting anything!

Quickstart guide for Terra devs [BT-623]

---

servers/cromwell/requirements.txt
servers/cromwell/tox.ini
servers/jm_utils/tox.ini
ui/package.json
ui/yarn.lock

I believe this should resolve all open Dependabot alerts. Also incorporates the fix from #772. Where possible, I cherry-picked Dependabot's changes into this PR.

WX-894 Security updates

---

servers/cromwell/requirements.txt
ui/yarn.lock

Based on https://github.com/DataBiosphere/job-manager/pull/779 to ensure these updates work with our new auth logic.

WX-954 WX-937 Security updates

---

README.md
TERRA_QUICKSTART.md
common-compose.yml
deploy/cromwell/docker-compose/README.md
deploy/quickstart/quick_start.py
docs/GettingStarted/QuickStart.md
ui/README.md
ui/package.json
ui/src/app/job-details/common/failures-table/failures-table.component.css
ui/src/app/job-details/panels/panels.component.css
ui/src/app/job-details/panels/panels.component.html
ui/src/app/job-details/resources/resources-table/resources-table.component.css
ui/src/app/job-details/resources/resources-table/resources-table.component.html
ui/src/app/job-details/resources/resources-table/resources-table.component.ts
ui/src/app/job-details/tabs/tabs.component.html

[AN-429] Make wf input text wrap

---

ui/src/app/job-details/common/debug-icons/debug-icons.component.spec.ts
ui/src/app/job-details/common/debug-icons/debug-icons.component.ts

We changed the format of these job ids, so need to adjust regex. Also discovered when trying to repro the issue with tests that many of our tests in this file were not actually working.

AN-704 Fix links to GCP batch console
