- .gitignore
- common-compose.yml
- cromwell-compose.yml
- dsub-google-compose.yml
- dsub-local-compose.yml
- servers/cromwell/README.md
Simplify running the job manager with cromwell as a backend by 
1. Making it easier to override the default `CROMWELL_URL` defined in `common-compose.yml`
2. Moving the location of the cromwell `config.json` to `/servers/cromwell/jobs` to remove the extra step of having to create a folder in your root directory (note: anyone who is currently running the job manager locally for cromwell will need to move `/private/etc/job-manager/config.json` to `/servers/cromwell/jobs`
> Simplify running job manager with cromwell

- servers/dsub/jobs/controllers/jobs_controller.py
- servers/dsub/jobs/controllers/utils/query_parameters.py
- servers/dsub/jobs/test/base_test_cases.py
`dstat` takes in create_time as seconds from epoch which it directly passes to the pipelines API. We've been passing in a datetime which doesn't work.
> [dsub] Fix support for querying by job start

- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
- servers/dsub/jobs/controllers/jobs_controller.py
- servers/jm_utils/jm_utils/page_tokens.py
- servers/jm_utils/jm_utils/test/test_page_tokens.py
This is a prerequisite for implementing the fixed `dsub` pagination strategy which is based upon querying the Pipelines API with a CreatedBefore parameter.
The only alteration to the behavior for cromwell is the change in `encode` and `decode` method names, and that `page_tokens` returns `None` rather than `0` when trying to decode a `None`. I updated cromwell's `jobs_controller` to handle that. 
I also removed a duplication of:
```
if not page_size:
page_size = _DEFAULT_PAGE_SIZE
```
in `page_from_offset`. It seems redundant to check that twice rather than do it at right away and know it is present from there forth. There was an associated test that `page_from_offset` can handle `None` which I removed.
> Update page_tokens to support created_before + offset_id tokens

- ui/src/app/job-list/table/table.component.ts
Previously, loading the table view multiple times would result in user-id (for dsub) being repeatedly appended to the table view multiple times.
> Don't mutate primaryColumns; teardown table

- servers/dsub/jobs/test/base_test_cases.py
- servers/dsub/jobs/test/test_jobs_controller_google.py
- servers/dsub/jobs/test/test_jobs_controller_local.py
- Increase timeout for google jobs to start to 5 minutes, should fix issues with jobs not being `RUNNING` after 2 minutes
- Reduce poll interval for local provider tests and add sleep to ensure job has started, fixing silent docker error:
```
Error response from daemon: Cannot kill container: dsub-sleep--circleci--180104-010812-353250: No such container: dsub-sleep--circleci--180104-010812-353250
```
> [dsub] Fix abort job test for google and local providers

- servers/dsub/jobs/controllers/jobs_controller.py
- servers/dsub/jobs/controllers/utils/job_ids.py
- servers/dsub/jobs/controllers/utils/labels.py
- servers/dsub/jobs/controllers/utils/query_parameters.py
- servers/dsub/jobs/test/base_test_cases.py
- servers/dsub/jobs/test/test_jobs_controller_google.py
- ui/src/app/job-details/panels/panels.component.html
- ui/src/environments/environment.dsub.google.ts
- ui/src/environments/environment.dsub.local.ts
- Support querying by `user-id`, `job-id`, and `task-id` labels. These are considered first class fields in `dstat`, but are jammed into `labels` in the common API. We have to translate back when querying by them.
- Add tests validating behavior and ensuring querying multi-tasks jobs works
- Also add `job-id` and `task-id` columns to the jobs list page. This will allow users to more easily construct queries for say all the running tasks left on a single dsub job. 
- Use a `+` rather than `:` to join components since projects with a URL prefix use a `:` to join.
> [dsub] Support querying by reserved labels and URL-prefixed projects fix

- servers/cromwell/jobs/controllers/jobs_controller.py
Sort tasks on the job details page by start time in the cromwell backend.
> Sort tasks by start time

- .circleci/config.yml
The CircleCI VMs have 2 cores which is used as the [default](https://github.com/tox-dev/detox/blob/master/detox/tox_proclimit.py#L17) number of parallel processes for `detox` . The dsub integration tests are not computationally intensive, they just take a while to wait for jobs to be started on google cloud. More concurrency should theoretically speed this up.
> [CI] Run detox tests with 8 parallel processes

- servers/dsub/Dockerfile.local
On my machine, sometimes local dsub failed to start up [1].
I'm able to repro with:
- ln -sf dsub-local-compose.yml docker-compose.yml
- docker-compose build dsub
- docker-compose up
Dockerfile.local was missing "rm -rf jm_utils". The other Dockerfile's have this. So the container had jm_utils in 2 places: /home/vmagent/app/jm_utils and in /env/lib/python2.7/site-packages. Due to syspath ordering, former is picked up. Former didn't have page_tokens.
I believe others weren't seeing this -- even with local dsub -- because depending on ordering of commands, their container might have had "rm -rf jm_utils" from Google-dsub Dockerfile.
[1]
Starting jobmanager_dsub_1 ... done
Attaching to jobmanager_dsub_1
dsub_1        | [2018-01-17 01:08:30 +0000] [1296] [INFO] Starting gunicorn 19.7.1
dsub_1 …
> Fix local dsub not starting up

- ui/package-lock.json
- ui/package.json
- ui/src/app/projects/projects.component.css
- ui/src/app/projects/projects.component.ts
- ui/src/app/shared/job-stream.ts
Went through the app and this didn't seem to break anything, surprisingly (aside from the project dropdown 30% width FYI @bfcrampton, in case I missed the purpose of that). Also required bumping TS to 2.4.
The latest angular release contains a paginator option for hiding pageSize, which is what we'd like to have on the jobs table.
> Upgrade to Angular 5

- ui/package-lock.json
- ui/package.json
Include `@types/angular` to resolve the following build error:
```
docker-compose -f dsub-google-compose.yml up
Recreating jobmanager_ui_1 ... 
Starting jobmanager_dsub_1 ... 
Recreating jobmanager_ui_1
Recreating jobmanager_ui_1 ... done
Recreating jobmanager_jobs-proxy_1 ... 
Recreating jobmanager_jobs-proxy_1 ... done
Attaching to jobmanager_dsub_1, jobmanager_ui_1, jobmanager_jobs-proxy_1
dsub_1        | [2018-02-07 18:45:54 +0000] [1] [INFO] Starting gunicorn 19.7.1
dsub_1        | [2018-02-07 18:45:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:8190 (1)
ui_1          | npm info it worked if it ends with ok
ui_1          | npm info using npm@5.3.0
ui_1          | npm info using node@v8.5.0
dsub_1        | [2018-02-07 18:45:54 +0000] [1] [INFO] Using worker: sync
dsub_1        | …
```
> Fix angular types error

- common-compose.yml
- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
The Cromwell `query` endpoint returns jobs from oldest to newest, but we want to display jobs from newest to oldest in the UI. 
This PR updates the `query` endpoint in the translation layer to: 
1. Make a request to the query endpoint to get the `totalResultsCount`. 
2. Calculate which page to request from the API based on the total number of pages and the current page in the UI, so that the results are retrieved from newest to oldest.
3. Query the Cromwell API (filtering out subworkflows) and continue getting results if the initial amount returned is less than `query.page_size`. 
Notes:
- This request can take 30+ seconds if there are a lot of subworkflows in the page of results that is requested, so this PR also increases the `timeout` in gunicorn to 60 seconds (the default is 30s)
- …
> List Cromwell jobs from newest to oldest 

- ui/package-lock.json
- ui/package.json
- ui/src/app/job-details/job-details.component.html
- ui/src/app/job-list/job-list.component.html
- ui/src/app/job-list/job-list.component.spec.ts
- ui/src/app/job-list/job-list.component.ts
- ui/src/app/job-list/table/table.component.html
- ui/src/app/job-list/table/table.component.spec.ts
- ui/src/app/job-list/table/table.component.ts
- ui/src/app/shared/header/header.component.css
- ui/src/app/shared/header/header.component.html
- ui/src/app/shared/header/header.component.spec.ts
- ui/src/app/shared/header/header.component.ts
- ui/src/app/shared/shared.module.ts
- ui/src/test.ts
- Refactor paginator from the table component, to the header; required restructuring the data flow between the job stream, data source, pagination control, table updates
- The job table no longer gets momentarily cleared out on navigation
- Refactor table to use the CDK model selection, including indeterminate state, e.g. if we have a mix of checked/unchecked -> select all now only selects the currently visible jobs
- Only show the aborted button if at least one selected job can be aborted
- Dropped the status tabs from the job details page (need to fully address the filter bar being there, but this was an easy incremental change to make in this PR)
- Move @types/angular to dev deps; it's odd that we need it at all since it just references Angular 1 stuff
> Move paginator to the header

- ui/src/app/job-list/job-list.component.spec.ts
- ui/src/app/shared/header/header.component.ts
The bug was that if you had a long list of jobs, the paginator would show "1-50 of 100" rather than "1-50 of many", until you interacted with the component, e.g. hover.
The cause of this issue is that `afterViewInit` gets run after the initial rendering. Modifying `_intl` also doesn't directly mutate anything that is rendered in the template, so ng doesn't pick up the update. Explicitly notifying the paginator of the change on initialization fixes this.
> Fix initial non-exhaustive paginator rendering

- servers/dsub/jobs/controllers/capabilities_controller.py
- servers/dsub/jobs/controllers/jobs_controller.py
- servers/dsub/jobs/controllers/utils/query_parameters.py
- servers/dsub/jobs/test/base_test_cases.py
- servers/dsub/jobs/test/test_jobs_controller_google.py
- Make `query.start` actually query by start time instead of submission
- Add support for `query.extensions.submission`
> [dsub] Implement querying by start time

- ui/src/app/core/core.module.ts
- ui/src/app/core/notify-loading.service.ts
- ui/src/app/job-list/job-list.component.css
- ui/src/app/job-list/job-list.component.html
- ui/src/app/job-list/job-list.component.spec.ts
- ui/src/app/job-list/job-list.component.ts
- ui/src/app/job-list/job-list.module.ts
- During all navigation, show an unobtrusive "Loading..." snackbar; this is a low-fidelity solution which doesn't cover the screen but provides user feedback that something is happening.
- This primarily covers projects -> jobs list, jobs list -> job details transitions
- During job list reloads, show a mat-spinner + white transparent overlay on the table only; this behaves specially due to the following requirements:
- In our ideal UX we'd like to leave the filter controls / query builder available during a query, e.g. if someone is typing in a series of chips, we don't want to block entry of the next chip on page load.
- The job list component is special anyways, since its a singleton and navigation to itself doesn't block on data load
- Harden the jobs list towards multiple concurrent …
> Add general loading + jobs table specific loading

- ui/src/app/shared/header/header.component.css
- ui/src/app/shared/header/header.component.html
- ui/src/app/shared/header/header.component.spec.ts
- ui/src/app/shared/header/header.component.ts
Simply hide the status counters if we have a non-exhaustive job stream. This may lead to slightly confusing behavior, but will help in a subset of cases.
A few ideas for future improvements:
1. Get a "total" count in ListOperations, thereby bypassing a need to materialize the full job list to populate these values.
2. Load a larger initial page; once we have a total count in ListOperations, we would also decide whether to load the full job list client side, depending on he total size of the stream.
3. Give an option to load everything client side. Possibly clicking "many" would yield a drop-down to load all?
4. Have a placeholder for non-exhaustive streams, with some helper text when you mouseover (and perhaps an option to load all).
> Add status counters for exhaustive job lists

- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/controllers/utils/task_statuses.py
- servers/dsub/jobs/controllers/utils/job_statuses.py
Fix the broken statuses of Cromwell task by mapping those atomic execution statuses to Job Manager's common API statuses. 
This PR avoids adding any detailed execution statuses to the capabilities endpoint for simplicity. Besides, some of the Cromwell execution statuses, for example, `Bypassed` or `RetryableFailure` are really rare and it doesn't make any sense to expose them to users. 
There are some discussions here: https://github.com/broadinstitute/cromwell/issues/3328
> [Cromwell] Fix the statuses of Cromwell tasks

- cromwell-compose-caas.yml
- cromwell-compose-dev.yml
- servers/cromwell/jobs/__main__.py
- servers/cromwell/jobs/controllers/capabilities_controller.py
- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/controllers/utils/auth.py
- servers/cromwell/jobs/test/test_auth_utils.py
- servers/cromwell/jobs/test/test_jobs_controller.py
- ui/.angular-cli.json
- ui/src/environments/environment.cromwell.caas.ts
Support making API requests to cromwell-as-a-service using a bearer token (requires google sign in to be enabled).
> Add support for cromwell-as-a-service

- servers/cromwell/jobs/__init__.py
Fix the cannot find application issue by adding back the import statement, which is necessary for gunicorn to find the application.
> [Cromwell] Fix the cannot find application issue

- ui/src/app/projects/projects.component.html
- ui/src/app/projects/projects.component.ts
Also add sorting to the projects list. This is necessary in the case where you have two projects with one name being the prefix of the other (ex: `bvdp-jmui-testing` and `bvdp-jmui-testing-2`). We'd like the shorter to be first so that if you type exactly `bvdp-jmui-testing` the exact match is auto-selected.
> [UI] Auto select top project on drop down

- ui/src/app/job-list/job-list.component.css
- ui/src/app/job-list/table/table.component.css
- ui/src/app/job-list/table/table.component.html
Make the job list table horizontally scrollable within the page. Fixes the bug where the query builder is cut off when there are too many columns in the table (overflow list tables). Also fixes the bug where the checkbox and job name appeared stacked on top of each other.
This is a precursor to pin selected-jobs controls to window bottom which I will follow up with in a separate PR.
> Fix table width sizing and long field truncation

- ui/src/app/job-list/table/table.component.css
- ui/src/app/job-list/table/table.component.html
- ui/src/app/job-list/table/table.component.spec.ts
- ui/src/app/job-list/table/table.component.ts
Fixes the 'stacking' problem of the checkbox and job name for long names:
Accomplished by separating the checkbox and job name columns. Also make the width of the dropdown column much smaller since it was unnecessarily big.
> [UI] Separate job name and checkbox columns

- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
This PR fixes the bug that filtering on labels is not working for Cromwell. 
The reason is that we didn't implement that functionality in Cromwell's controllers before.
> [Bug] Fix the issue that filtering on labels doesn't work for Cromwell.

- ui/src/app/shared/header/header.component.ts
check for query and query string before searching
see https://elastc.com/c/jPo5zc1X/287-job-list-drop-the-q-param-entirely-when-there-are-0-filters
> Job list: drop the "q" param entirely when there are 0 filters

- common-compose.yml
- cromwell-compose-caas.yml
- cromwell-compose-dev.yml
- cromwell-compose-staging.yml
- dsub-google-compose.yml
- dsub-local-compose.yml
- nginx.dev.conf
"api" has a DNS mapping now internally for us. Apparently our workstation DNS mapping supersedes the internal docker network.
I couldn't figure out how to reconfigure that - switching to an internal only docker network makes the proxy inaccessible locally. So I took the easy way out and just used a different service name.
> Fix local development for Google workstations

- servers/dsub/jobs/controllers/utils/extensions.py
This is needed for the local provider where '_SCRIPT' is not set.
> [dsub] Correctly check if _SCRIPT exists in envs

- ui/README.md
- ui/package.json
This only works if you run `npm test` directly (not if you run `ng test`), but at least it also serves as documentation of the flag.
> Preset --sourcemaps=false to improve test failures

- common-compose.yml
This causes problems with our docker compose setup. If we leave this setting on, then the Python server will generate .pyc files within docker. This causes problems because it writes files to our source directory (via mounted volume) and we run docker as "root" (the files are owned by that user).
The end result is write-protected .pyc files in the source directory, which means you'll need to manually remove them or use sudo if you want to rebuild the local docker images.
Furthermore, I don't like the potential issues you hit if you remove a py source file, but forget to move the pyc file.
> Cromwell shim: don't write python pyc files

- README.md
- scripts/rebuild_swagger.sh
One day it might be nice to coordinate the entire rebuild process using a make script, but until then this script automates the steps in the [Updating the API using Swagger Codegen](https://github.com/DataBiosphere/job-manager/tree/cjl_rebuild_swagger_script#updating-the-api-using-swagger-codegen) section of the docs (link goes to my updated version of the docs).
EDIT: I've also removed the suggestion to `brew install swagger-codegen` since when I did that it was missing a key `typescript-angular2` generator class.
> Automate 'Updating the API using swagger-codegen'

- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/tox.ini
- servers/dsub/tox.ini
passing `--logging-level=WARN` to calls to `nosetests` for back-end testing
> pass parameters to nosetest to reduce log spam on backend test logs

- servers/dsub/jobs/test/test_jobs_controller_google.py
Seems that Google provider test is excluded on last merge, fixing the bug.
> google provider test fixing

- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
~~Shows up in the status pane. Closes #318~~ 
---
EDIT: Ignore that picture! I moved this back to the "Tasks" section where it was before. That doesn't feel like a great final location for it because ultimately we should be able to draw a timing diagram for `dsub` jobs too, and they don't use the tasks panel, but for now it's good enough
> Re-add link to timing diagram

- README.md
I've removed the "manual process" section since that wouldn't generate the `.md5` files which the services are keying off for "should I start yet".
> Usage documentation for the rebuild-swagger service

- servers/dsub/jobs/controllers/aggregation_controller.py
- servers/dsub/jobs/controllers/capabilities_controller.py
- servers/dsub/jobs/controllers/jobs_controller.py
- servers/dsub/jobs/controllers/utils/job_ids.py
- servers/dsub/jobs/controllers/utils/jobs_generator.py
- servers/dsub/jobs/controllers/utils/labels.py
- servers/dsub/jobs/controllers/utils/query_parameters.py
- servers/dsub/jobs/test/base_test_cases.py
Added a new "Attempt" column for the dsub job manager. Also supports querying by attempt, and now doesn't break when you try to see the details page for a retried job.
> Support retryable dsub jobs

- .circleci/config.yml
https://github.com/tox-dev/detox/issues/33
Debug process:
- Search Google/tox for issues mentioning this, didn't find any
- Compare circle outputs from the failing vs successful runs, particularly the versions installed in the step "Install detox and yapf"
- Rerun with SSH - SSH into Circle to reproduce the issue
- Noticed different tox version installed across runs, try downgrading to 3.4.0 (last working version)
- Ran the tests again and verified this fixes
- Realized this repros with detox but not tox alone, looked at detox repo and found the issue: https://github.com/tox-dev/detox/issues/33
> Pin to older version of tox to fix CI

- ui/src/app/shared/utils/url-search-params.utils.ts
I realized that, without this change, the `hideArchived` query extension will show up as an option in the query builder.  This change filters out any `boolean` query extensions from the menu.
> Hide boolean query extensions from query builder

- ui/src/app/job-list/table/table.component.spec.ts
- ui/src/app/job-list/table/table.component.ts
Fix bug in logic for default bulk edit fields where blank label fields are displayed as `(multiple)`
> fix bulk edit fields default

- servers/cromwell/jobs/controllers/jobs_controller.py
- ui/src/app/shared/utils/url-search-params.utils.ts
Filtering by a label value with whitespace in it currently doesn't work. I added URL decoding to the UI and Cromwell shim layer.
> fix for whitespace in label values

- README.md
- docs/GettingStarted/QuickStart.md
- docs/index.md
- mkdocs.yml
It's a little clunky to have our user and developer docs overlapping - let's use readthedocs to host our user- and deployer-facing documentation in a slightly less intimidating place?
This one works:
- Current content: https://data-biosphere-job-manager.readthedocs.io/en/cjl_rtd/
These will work when we make a commit to master and/or a new tag:
- Master branch: https://data-biosphere-job-manager.readthedocs.io/en/latest/
- Tagged branch: https://data-biosphere-job-manager.readthedocs.io/en/stable/
> Move user docs into ReadTheDocs

- ui/src/app/core/settings.service.ts
If a user's browser already has JMUI settings saved in local storage for a project before the `hideArchived` functionality is enabled, and then it is enabled, it doesn't show up as a possible setting.
> added code to handle hideArchived being added to existing saved project settings

- ui/src/app/shared/header/chips/filter-chip.component.ts
Because a user can select multiple statuses to filter the job list by, change the `click` behavior so that the user can do so without having to choose `statuses` from the query builder menu each time.
Closes #437
> set different filter behavior for status checkboxes

- ui/src/app/job-list/table/table.component.css
- ui/src/app/job-list/table/table.component.html
After discussion with the designer and the product manager, implemented small changes to task details page:
Before:
After:
(also added tool tip for truncated filter) 
**Note:** Did not remove the 'abort' button, it's just not available for this job.
Closes #519
> small design changes to job details menu

- api/jobs.yaml
- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
- servers/dsub/jobs/controllers/utils/jobs_generator.py
- servers/dsub/jobs/controllers/utils/query_parameters.py
- servers/dsub/jobs/test/base_google_test_cases.py
- servers/dsub/jobs/test/base_test_cases.py
- ui/src/app/dashboard/dashboard.component.spec.ts
- ui/src/app/dashboard/grouped-summary/grouped-summary.component.ts
- ui/src/app/dashboard/total-summary/total-summary.component.ts
- ui/src/app/shared/common.ts
- ui/src/app/shared/header/chips/filter-chip.component.html
- ui/src/app/shared/header/chips/filter-chip.component.ts
- ui/src/app/shared/header/header.component.html
- ui/src/app/shared/header/header.component.spec.ts
- ui/src/app/shared/header/header.component.ts
- ui/src/app/shared/utils/url-search-params-utils.spec.ts
- ui/src/app/shared/utils/url-search-params.utils.ts
- ui/src/app/testing/fake-job-manager.service.ts
In response to user testing results, make the options in the query builder filter drop down correspond to the column headings in the job listing.
Closes #520
> Make filter options consistent with the job list columns

- ui/src/app/job-details/tasks/tasks.component.css
- ui/src/app/job-details/tasks/tasks.component.html
- ui/src/app/job-details/tasks/tasks.component.spec.ts
- ui/src/app/shared/common.ts
- change the `aborted`, `aborting`, `failed`, `on hold`, and `succeeded` icons in response to user testing
- added tooltips for shard status icons
Closes #517
> Make job/task status icons more intuitive

- ui/src/app/job-list/job-list.component.spec.ts
- ui/src/app/shared/header/header.component.html
- ui/src/app/shared/header/header.component.spec.ts
- ui/src/app/shared/header/header.component.ts
After noting issues during user testing, change the quick filter status buttons to correspond to just one status.  After feedback from demo, add status icon.
Before:
After:
Closes #518
> improve the clarity of the the status buttons

- ui/src/app/shared/header/header.component.css
- ui/src/app/shared/header/header.component.html
- ui/src/app/shared/header/header.component.ts
before:
after:
Will not clear the `projectId` chip, as requested.
Closes #388
> Add button to clear the query builder chips

- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_task_statuses.py
Take all returned shard statuses into account when figuring out the status of a scattered task.
Closes #542
> Return more accurate scattered task status

- ui/src/app/job-details/common/failures-table/failures-table.component.ts
- ui/src/app/job-details/tabs/tabs.component.ts
As of recently, `getResourceURL` links do not work with files that are behind authentication, so this replaces them with calls to `getDirectoryBrowserURL`.
> replaced calls to getResourceURL with getDirectoryBrowserURL

- CHANGELOG.md
- ui/src/app/core/auth.service.ts
- ui/src/app/dashboard/dashboard.component.spec.ts
- ui/src/app/job-details/tabs/tabs.component.spec.ts
- ui/src/app/job-list/job-list.component.spec.ts
- ui/src/app/shared/header/header.component.spec.ts
Now, when user has an `authorization` section in their capabilities config (or something else that causes `gapi.auth2` to fail, the error is caught and displayed to the user:
instead of just failing and dumping the error message in the javascript console.
Closes #441
> Handle auth failure more elegantly

- CHANGELOG.md
- ui/src/app/shared/header/header.component.ts
Addresses #577 by forcing a reload of the `/jobs` page while the session is logged out.
> Force reload of the jobs page on sign out

- ui/src/app/job-details/common/failures-table/failures-table.component.css
- ui/src/app/job-details/panels/panels.component.css
> adjusted styles for cards on job details page

- CHANGELOG.md
- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
- servers/cromwell/jobs/test/test_task_statuses.py
> Changed how scattered tasks' status, duration and attempts are calculated

- CHANGELOG.md
- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
- ui/src/app/job-details/common/failures-table/failures-table.component.css
- ui/src/app/job-details/job-details.component.ts
- added handling of workflow errors that aren't embedded in the 'calls' section of the metadata
- small CSS tweaks to display of error info in job details
Closes #588
> Improvements to parsing of error information in metadata

- CHANGELOG.md
- ui/src/app/job-list/job-list.component.ts
Remove 'loading' screen when user has made an invalid query on job list page so the user can make changes.
Closes #569
> More useful UI behavior when user submits bad jobs query

- CHANGELOG.md
- ui/src/app/job-details/common/debug-icons/debug-icons.component.css
- ui/src/app/job-details/common/debug-icons/debug-icons.component.html
- ui/src/app/job-details/common/debug-icons/debug-icons.component.spec.ts
- ui/src/app/job-details/common/debug-icons/debug-icons.component.ts
- ui/src/app/job-details/common/failures-table/failures-table.component.html
- ui/src/app/job-details/common/failures-table/failures-table.component.ts
- ui/src/app/job-details/job-details.component.spec.ts
- ui/src/app/job-details/job-details.module.ts
- ui/src/app/job-details/panels/panels.component.spec.ts
- ui/src/app/job-details/resources/resources-table/resources-table.component.html
- ui/src/app/job-details/tabs/tabs.component.html
- ui/src/app/job-details/tabs/tabs.component.spec.ts
- ui/src/app/job-details/tabs/tabs.component.ts
Reduce possibility of certain icons behaving/linking in a different way dependent on context.
Closes #602 
Closes #609
> Move all output icons into one component and re-use

- CHANGELOG.md
- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
Undo bug introduced in previous feature (added execution events to shards in scattered tasks) that removed needed `end` time from scattered tasks.
> Fix duration bug for scattered tasks

- CHANGELOG.md
- api/jobs.yaml
- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
- ui/src/app/job-details/common/debug-icons/debug-icons.component.css
- ui/src/app/job-details/common/failures-table/failures-table.component.css
- ui/src/app/job-details/common/failures-table/failures-table.component.html
- ui/src/app/job-details/job-details.component.css
- ui/src/app/job-details/panels/panels.component.css
- ui/src/app/job-details/panels/panels.component.html
- ui/src/app/job-details/tabs/tabs.component.css
- ui/src/app/job-details/tabs/tabs.component.ts
Also, add link to sub-workflow from parent workflow error card.
Before:
After:
(on hover)
Closes #635
> Show sub-workflow error on parent workflow job details

- CHANGELOG.md
- ui/src/app/job-details/common/debug-icons/debug-icons.component.html
> changed color of error message icon

- CHANGELOG.md
- ui/src/polyfills.ts
Fix suggested here: https://communities.vmware.com/message/2717325#2717325
Closes #639
> Fix display of Clarity icons in Firefox

- CHANGELOG.md
- api/jobs.yaml
- servers/cromwell/README.md
- ui/src/app/app.component.ts
- ui/src/app/core/auth.service.ts
- ui/src/app/sign-in/sign-in.component.ts
Auto-sign-out will be enabled if the `capabilities_config.json` contains the following in the `authentication` section:
>     "forcedLogoutDomains": [
>       <one or more domain>
>     ],
>     "forcedLogoutTime": <number of milliseconds of inactivity that will result in sign-out>
Closes #623
> Add in automatic sign out after an interval of inactivity

- CHANGELOG.md
- servers/cromwell/jobs/controllers/jobs_controller.py
Make sure that a missing `start` time in a task will not result in weird or broken behavior by changing the fallback value from `now()` to `end`.
Closes https://broadworkbench.atlassian.net/browse/BA-4978.
> Gracefully handle tasks with no start datetime [BA-4978]

- CHANGELOG.md
- ui/src/app/core/auth.service.ts
- ui/src/app/core/capabilities-activator.service.ts
- ui/src/app/job-details/common/debug-icons/debug-icons.component.ts
Sorted out order of operations for auth and capabilities services so that user is not redirected to the log in screen unnecessarily.
Closes https://broadworkbench.atlassian.net/browse/BA-5793
> fix redirect bug [BA-5793]

- CHANGELOG.md
- ui/src/app/job-details/tabs/tabs.component.ts
Default to Errors tab if job has failed or been aborted and there are error messages.
Closes https://broadworkbench.atlassian.net/browse/BA-5893.
> Show errors tab by default in certain circumstances [BA-5893]

- CHANGELOG.md
- api/jobs.yaml
- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
- ui/src/app/job-details/common/attempt/attempt.component.css
- ui/src/app/job-details/common/attempt/attempt.component.html
- ui/src/app/job-details/common/debug-icons/debug-icons.component.html
- ui/src/app/job-details/common/debug-icons/debug-icons.component.spec.ts
- ui/src/app/job-details/common/debug-icons/debug-icons.component.ts
- ui/src/app/job-details/common/failures-table/failures-table.component.css
- ui/src/app/job-details/common/failures-table/failures-table.component.html
- ui/src/app/job-details/tabs/scattered-attempts/scattered-attempts.component.css
- ui/src/app/job-details/tabs/scattered-attempts/scattered-attempts.component.html
- ui/src/app/job-details/tabs/tabs.component.css
- ui/src/app/job-details/tabs/tabs.component.html
- ui/src/app/job-details/tabs/tabs.component.spec.ts
- ui/src/app/job-details/tabs/tabs.component.ts
- removed stdout and stderr logs, since the content is contained in the backend log
- increased max size of backend log to 500KB
Before:
After:
Closes https://broadworkbench.atlassian.net/browse/BA-5907
> Display only the backend log (no more stdout and stderr) [BA-5907]

- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_jobs_controller.py
- ui/src/app/job-details/tabs/scattered-attempts/scattered-attempts.component.ts
- ui/src/app/job-details/tabs/tabs.component.ts
With aliasing (e.g. `call subwf.subwf as alice`) there is no way to be sure of the full key for a task in the `calls` object in Cromwell metadata.  But the task name is always the same (e.g. the "taskName" in `alias.taskName`), so just check for that when getting attempts.
Closes https://broadworkbench.atlassian.net/browse/BA-5972
> Handle parsing for task/shard attempts correctly [BA-5972]

- CHANGELOG.md
- ui/src/app/job-details/common/failures-table/failures-table.component.html
Before:
Add:
Closes https://broadworkbench.atlassian.net/browse/BA-6003
> fixed display of workflow-level errors in error card [BA-6003]

- CHANGELOG.md
- servers/cromwell/jobs/controllers/jobs_controller.py
The Cromwell shim layer was not setting the end time, so duration was incorrectly calculated within the UI.
> fixed duration time for aborted scattered tasks [WA-79]

- cromwell-caas-compose.yml
- servers/cromwell/README.md
- servers/cromwell/jobs/__main__.py
- servers/cromwell/jobs/controllers/jobs_controller.py
- servers/cromwell/jobs/test/test_auth_utils.py
In general, we are deploying JMUI against a Cromwell instance that uses OAuth (an OIDC based AuthProxy) but does not have CromIAM. This is affected by https://github.com/DataBiosphere/job-manager/pull/576 that subworkflows are showing up in the job details page.
See discussion here: https://broadinstitute.slack.com/archives/CFA6Q2QBU/p1599146973203800?thread_ts=1599145468.201200&cid=CFA6Q2QBU
Add a `INCLUDE_SUBWORKFLOWS` flag and set it to `True` by default so subworkflows are filtered out by default as well. non-CromIAM Cromwell backends that are using OAuth should set it to `False`.
> Fix an issue that messes up subworkflows in specific Cromwells

- .github/workflows/trivy.yml
- ui/Dockerfile
This change adds Trivy security scan for the Docker image, as discussed in the Workbench Cross-Team meeting.
The action will run on every PR and give you feedback if the Docker image contains critical OS vulnerabilities.
More info:
https://github.com/broadinstitute/dsp-appsec-trivy-action
https://github.com/broadinstitute/dsp-appsec-blessed-images
> [BT-85] [BT-78] Add AppSec GitHub Trivy Action

- README.md
- servers/cromwell/Dockerfile
- ui/Dockerfile
```
docker run -it aquasec/trivy:latest image --ignore-unfixed --vuln-type os us.gcr.io/broad-dsp-gcr-public/job-manager-ui:v1.6.0_rc5
2021-07-29T18:09:17.611Z	INFO	Need to update DB
2021-07-29T18:09:17.611Z	INFO	Downloading DB...
22.65 MiB / 22.65 MiB [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 20.87 MiB p/s 2s
2021-07-29T18:09:20.454Z	INFO	Detected OS: alpine
2021-07-29T18:09:20.454Z	INFO	Detecting Alpine vulnerabilities...
us.gcr.io/broad-dsp-gcr-public/job-manager-ui:v1.6.0_rc5 (alpine 3.14.0)
========================================================================
Total: 9 (UNKNOWN: 1, LOW: 4, MEDIUM: 4, HIGH: 0, CRITICAL: 0) …
```
> Resolve all Job Manager HIGHs & update docs [BW-752]

- .circleci/config.yml
- ui/Dockerfile
- ui/Dockerfile.dev
Narrow upgrade of node 12 -> 14 because node 12 is EOL. Note that the dev docker file already specified node 14, so it is not included in these changes.
I ran the app locally and clicked around everything I could find, and it all seemed to work normally.
> BT-628 Upgrade node to 14

- ui/package-lock.json
Update usage of the `extend` library to at least `3.0.2`.
After initially believing that this was actually a prod dependency, further investigation makes me unsure now. The closest links I could find were through `request:2.81.0`, but that traces back to `chokidar` (a file watcher for running development mode, via `fsevents:1.1.3` -> `node-pre-gyp:0.6.39`) and `less:2.7.3` (via `@angular/cli:1.6.5`).
However, since I believe I've already done the work to update this, I'd like to push it through. I think there's still value to be gained in confirming that this will clear the SourceClear warning.
> [BT-720] Update `extend`

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/core/initial-error/initial-error.component.html
- ui/src/app/pagenotfound/pagenotfound.component.css
- ui/src/app/pagenotfound/pagenotfound.component.html
- ui/src/app/pagenotfound/pagenotfound.component.spec.ts
- ui/src/app/pagenotfound/pagenotfound.component.ts
At least temporarily, disable nonfunctional job list page.
> BT-758 404 for job list

- servers/cromwell/requirements-to-freeze.txt
- servers/cromwell/requirements.txt
I edited `requirements.txt` and ran
```
pip install -r requirements.txt
```
Then I built a new container
```
docker build -t us.gcr.io/broad-dsp-gcr-public/job-manager-api-cromwell:v1.7.3-a1 . -f servers/cromwell/Dockerfile
```
and entered it
```
docker run -it --entrypoint /bin/bash us.gcr.io/broad-dsp-gcr-public/job-manager-api-cromwell:v1.7.3-a1
```
to verify the new library took effect, which it did:
```
Name: gevent
Version: 23.9.0
Summary: Coroutine-based network library
Home-page: http://www.gevent.org/
Author: Denis Bilenko
Author-email: denis.bilenko@gmail.com
License: MIT
Location: /usr/local/lib/python3.10/site-packages
Requires: greenlet, zope.event, zope.interface
Required-by: 
```
> WX-1305 Upgrade `gevent` to 23.9

- README.md
- ui/src/app/job-details/panels/panels.component.html
Abort and "Go back" buttons are in the same place in the job manager UI
A user can easily accidentally hit the abort button when trying to go back
(Also updated the readme because docker-compose is deprecated)
> Move abort button

- ui/src/app/job-details/common/debug-icons/debug-icons.component.html
- ui/src/app/job-details/common/debug-icons/debug-icons.component.spec.ts
- ui/src/app/job-details/common/debug-icons/debug-icons.component.ts
This change lets users easily access GCP Batch operation details by linking to be GCP console. Behavior for PAPI should be unchanged, tested in dev to confirm.
> AN-177 Batch compute details
